In [0]:
import tensorflow as tf
import numpy as np

In [105]:
#valores de entrada
entrada = np.array( [[0, 0], [0, 1], [1, 0], [1, 1]])
entrada

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [106]:
#valores esperados na saída

saida_esperada = np.array([[1],[0],[0],[1]])
saida_esperada

array([[1],
       [0],
       [0],
       [1]])

In [0]:
neuronio_entrada = 2
neuronio_oculta = 3
neuronio_saida = 1

In [0]:
#                                                [linha]           [coluna]
pesos = {'oculta': tf.Variable(tf.random_normal([neuronio_entrada, neuronio_oculta]), name= 'pesos_oculta'),
         'saida' : tf.Variable(tf.random_normal([neuronio_oculta, neuronio_saida]), name = 'pesos_saida')}

In [109]:
type(pesos['oculta'])

tensorflow.python.ops.variables.RefVariable

In [0]:
init = tf.global_variables_initializer()

In [0]:
bias = {'oculta': tf.Variable(tf.random_normal([neuronio_oculta]), name = 'bias_oculta'),
        'saida' : tf.Variable(tf.random_normal([neuronio_saida]), name = 'bias_saida')}

In [0]:
xph = tf.placeholder(tf.float32, [4, neuronio_entrada], name='xph')
yph = tf.placeholder(tf.float32, [4, neuronio_saida], name='yph')

In [0]:
camada_oculta = tf.add(tf.matmul(xph, pesos['oculta']), bias['oculta'])
camada_oculta_ativacao = tf.sigmoid(camada_oculta)
camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, pesos['saida']), bias['saida'])
camada_saida_ativacao = tf.sigmoid(camada_saida)

In [0]:
erro = tf.losses.mean_squared_error(yph, camada_saida_ativacao) # os argumentos do tf.losses.mean_squared_error(respostasVerdadeiras, respotaDoAlgoritmo) 
otimizador = tf.train.GradientDescentOptimizer(learning_rate=0.3).minimize(erro)

In [125]:
with tf.Session() as sess:
  sess.run(init)
  #print(sess.run(pesos['oculta']))
  #print(sess.run(pesos['saida']))
  #print(sess.run(camada_oculta, feed_dict= {xph: entrada}))
  #print(sess.run(camada_oculta_ativacao, feed_dict= {xph: entrada}))
  #print(sess.run(camada_saida, feed_dict= {xph: entrada}))
  #print(sess.run(camada_saida_ativacao, feed_dict= {xph: entrada}))
  for epoca in range(10000):
    erro_medio = 0
    _, custo = sess.run([otimizador, erro], feed_dict={xph: entrada, yph:saida_esperada})
    if epoca % 200 == 0:
      erro_medio += custo/4
      print(erro_medio)
  peso_final, bias_final = sess.run([pesos, bias])

0.06278061121702194
0.06245347484946251
0.06237373501062393
0.06226148456335068
0.062069330364465714
0.06170616298913956
0.06099097058176994
0.059590309858322144
0.05700703710317612
0.052942488342523575
0.04807238653302193
0.043365538120269775
0.03819970041513443
0.030800852924585342
0.022014379501342773
0.014741431921720505
0.010053163394331932
0.007195271551609039
0.00540774455294013
0.004236425738781691
0.003431900404393673
0.002855736995115876
0.002428144682198763
0.0021011456847190857
0.0018446596805006266
0.0016391277313232422
0.0014713804703205824
0.001332303392700851
0.0012154106516391039
0.0011159880086779594
0.0010305288014933467
0.0009563904022797942
0.0008915390353649855
0.0008343895897269249
0.0007836898439563811
0.0007384424097836018
0.000697838026098907
0.00066121865529567
0.0006280408706516027
0.0005978579865768552
0.0005702902562916279
0.0005450221942737699
0.0005217840662226081
0.0005003500264137983
0.00048052106285467744
0.0004621276166290045
0.0004450241685844958
0.

In [0]:
peso_final

In [0]:
bias_final

In [0]:
#@title Teste
camada_oculta_teste = tf.add(tf.matmul(xph, peso_final['oculta']), bias_final['oculta'])
camada_oculta_ativacao_teste = tf.sigmoid(camada_oculta_teste)
camada_saida_teste = tf.add(tf.matmul(camada_oculta_ativacao_teste, peso_final['saida']), bias_final['saida'])
camada_saida_ativacao_teste = tf.sigmoid(camada_saida_teste)

In [127]:
with tf.Session() as sess:
  sess.run(init)
  print(sess.run(camada_saida_ativacao_teste, feed_dict = {xph: entrada}))

[[0.97953963]
 [0.03595009]
 [0.04559279]
 [0.9509579 ]]
