In [0]:
import tensorflow as tf
import numpy as np

In [57]:
#valores de entrada
entrada = np.array( [[0, 0],
                     [0, 1],
                     [1, 0],
                     [1, 1]])
entrada

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [58]:
#valores esperados na saída

saida_esperada = np.array([[0.0],[0.0],[0.0],[1.0]])
saida_esperada

array([[0.],
       [0.],
       [0.],
       [1.]])

In [0]:
pesos = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))#tf.zeros cria uma matriz de zeros com 2 linhas e 1 coluna

In [0]:
def step(x):
  return tf.cast(tf.to_float(tf.math.greater_equal(x, 1)), tf.float64)

In [0]:
init = tf.global_variables_initializer()

In [0]:
camada_saida = tf.matmul(entrada, pesos)

In [0]:
camada_saida_ativacao = step(camada_saida)

In [0]:
erro = tf.subtract(saida_esperada, camada_saida_ativacao)

In [0]:
delta = tf.matmul(entrada, erro, transpose_a= True) #transpose_a transpõe a matriz x

In [0]:
treinamento = tf.assign(pesos, tf.add(pesos ,tf.multiply(delta, 0.1))) #criando novos pesos para a rede neural

In [81]:
with tf.Session() as sess:
  sess.run(init)
  #print(sess.run(pesos))
  #print(sess.run(camada_saida))
  #print('\n')
  #print(sess.run(camada_saida_ativacao))
  #print('\n')
  #print(sess.run(erro))
  print(sess.run(treinamento))
  
  epoca = 0
  
  for i in range(15):
    epoca += 1
    
    erro_total, _ = sess.run([erro, treinamento])
    erro_soma = tf.reduce_sum(erro_total)
    print("epoca: ", epoca, "Erro: ", sess.run(erro_soma))
    if erro_soma.eval() == 0:
      break
    pesos_final = sess.run(pesos)

[[0.1]
 [0.1]]
('epoca: ', 1, 'Erro: ', 1.0)
('epoca: ', 2, 'Erro: ', 1.0)
('epoca: ', 3, 'Erro: ', 1.0)
('epoca: ', 4, 'Erro: ', 1.0)
('epoca: ', 5, 'Erro: ', 0.0)


In [75]:
#teste
camada_saida_teste = tf.matmul(entrada, pesos_final)
camada_saida_ativacao_teste = step(camada_saida_teste)
with tf.Session() as sess:
  sess.run(init)
  print(sess.run(camada_saida_ativacao_teste))

[[0.]
 [0.]
 [0.]
 [1.]]
