In [0]:
from google.colab import drive
drive.mount('/content/drive/')

In [0]:
!ls "/content/drive/My Drive/data_set/"

census.csv  house-prices.csv


In [0]:
import pandas as pd
base = pd.read_csv('drive/My Drive/data_set/census.csv')

In [0]:
base.head()

In [0]:
base['income'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [0]:
base.shape

(32561, 15)

In [0]:
x = base.iloc[:, 0:14].values #.values transforma o vetor em numpy array
y = base.iloc[:, 14].values

In [0]:
x

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [0]:
y

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [0]:
x[0]

array([39, ' State-gov', 77516, ' Bachelors', 13, ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', 2174, 0, 40,
       ' United-States'], dtype=object)

In [0]:
#Preprocessamento dos dados, transformando variáveis string em números
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x[:, 1] = label_encoder.fit_transform(x[:, 1])
x[:, 3] = label_encoder.fit_transform(x[:, 3])
x[:, 5] = label_encoder.fit_transform(x[:, 5])
x[:, 6] = label_encoder.fit_transform(x[:, 6])
x[:, 7] = label_encoder.fit_transform(x[:, 7])
x[:, 8] = label_encoder.fit_transform(x[:, 8])
x[:, 9] = label_encoder.fit_transform(x[:, 9])
x[:, 13] = label_encoder.fit_transform(x[:, 13])

In [0]:
x[1]

array([50, 6, 83311, 9, 13, 2, 4, 0, 4, 1, 0, 0, 13, 39], dtype=object)

In [0]:
#Escalonando os valores de x
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x = scaler_x.fit_transform(x)

/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [0]:
x[0]

array([ 0.03067056,  2.15057856, -1.06361075, -0.33543693,  1.13473876,
        0.92163395, -1.3178091 , -0.27780504,  0.39366753,  0.70307135,
        0.1484529 , -0.21665953, -0.03542945,  0.29156857])

In [0]:
#Segregando os dados em dados de treinamento e teste
from sklearn.model_selection import train_test_split
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x, y, test_size=0.3)

In [0]:
x_treinamento.shape

(22792, 14)

In [0]:
#Utilizando o algoritmo de Regressao logística, ou seja, o algoritmo de classificacao
from sklearn.linear_model import LogisticRegression
classificador = LogisticRegression(max_iter = 10000) # max_iter é a mesma coisa de épocas
classificador.fit(x_treinamento, y_treinamento) # executamento propriamento o algoritmo de classificacao

/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=10000, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
previsoes = classificador.predict(x_teste)

In [0]:
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' >50K', ' <=50K'],
      dtype=object)

In [0]:
#Examinando o desempenho do algoritmo
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste, previsoes)

In [0]:
taxa_acerto

0.8269014228682567